name: "github pages"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install Nix"
        uses: "cachix/install-nix-action@v18"
        with:
          extra_nix_config: |-
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            accept-flake-config = true

      - name: "Checkout sources"
        uses: "actions/checkout@v3"

      - name: "Build"
        run: |-
          export URL_PREFIX="https://zentriamc.github.io/direnv-stdlib"
          nix develop .#ci --command "./ci/publish.sh"

      - name: "Deploy"
        uses: "peaceiris/actions-gh-pages@v3"
        if: "github.ref == 'refs/heads/master'"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./dist"
